// Code generated by mockery v2.53.5. DO NOT EDIT.

package infrastructure_mock

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

// DeleteUsersUserId provides a mock function with given fields: w, r, userId
func (_m *ServerInterface) DeleteUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	_m.Called(w, r, userId)
}

// GetUsersUserId provides a mock function with given fields: w, r, userId
func (_m *ServerInterface) GetUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	_m.Called(w, r, userId)
}

// PostUsers provides a mock function with given fields: w, r
func (_m *ServerInterface) PostUsers(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// PutUsersUserId provides a mock function with given fields: w, r, userId
func (_m *ServerInterface) PutUsersUserId(w http.ResponseWriter, r *http.Request, userId string) {
	_m.Called(w, r, userId)
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
