openapi: 3.0.3
info:
  title: API
  version: 1.0.0

paths:
  /users:
    post:
      tags: 
        - user
      summary: Create a new user
      description: API to create a new user in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPost'
      responses:
        '201':
          description: User successfully created
        '400':
          description: Invalid request (missing or incorrect data)
        '404':
          description: Related resource not found
        '500':
          description: Internal server error
    get:
      tags: 
        - user
      summary: Get users
      description: API get users in the system
      parameters:
        - name: offset
          in: query
          description: The number of items to skip before starting to collect the result set
          required: false
          schema:
            type: integer
            example: 0
        - name: limit
          in: query
          description: The maximum number of users to return
          required: false
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: User successfully created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid request (missing or incorrect data)
        '404':
          description: Related resource not found
        '500':
          description: Internal server error
  /users/{user_id}:
    get:
      tags: 
        - user
      summary: Get specific user
      description: Api get user in the system
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid request (missing or incorrect data)
        '404':
          description: User not found
        '500':
          description: Internal server error
    put:
      tags: 
        - user
      summary: Update specific user
      description: Api update user in the system
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPut'
      responses:
        '200':
          description: Successfully retrieved user
        '400':
          description: Invalid request (missing or incorrect data)
        '404':
          description: User not found
        '500':
          description: Internal server error
    delete:
      tags: 
        - user
      summary: Delete specific user
      description: Api delete user in the system
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved user
        '400':
          description: Invalid request (missing or incorrect data)
        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  schemas:
    UserPost:
      $ref: './request/user/post.yaml#/components/schemas/UserPost'
    UserPut:
      $ref: './request/user/put.yaml#/components/schemas/UserPut'
    UserResponse:
      $ref: './response/user.yaml#/components/schemas/UserResponse'
