// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        string         `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp without time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone" json:"deleted_at"`
	Email     string         `gorm:"column:email;type:character varying(255);not null" json:"email"`
	Phone     string         `gorm:"column:phone;type:character varying(255)" json:"phone"`
	Name      string         `gorm:"column:name;type:character varying(255);not null" json:"name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
