// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JSONResponse is an autogenerated mock type for the JSONResponse type
type JSONResponse struct {
	mock.Mock
}

// Failure provides a mock function with given fields: err
func (_m *JSONResponse) Failure(err error) {
	_m.Called(err)
}

// Success provides a mock function with given fields: status, response
func (_m *JSONResponse) Success(status int, response interface{}) error {
	ret := _m.Called(status, response)

	if len(ret) == 0 {
		panic("no return value specified for Success")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, interface{}) error); ok {
		r0 = rf(status, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJSONResponse creates a new instance of JSONResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJSONResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *JSONResponse {
	mock := &JSONResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
