services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${SECRET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SECRET_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SECRET_POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
