services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${SECRET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SECRET_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SECRET_POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SECRET_POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .          # directory containing Dockerfile
      dockerfile: Dockerfile
    container_name: order-server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
    - .env
volumes:
  pgdata:

